# Duarte Martinho - STUDENT NUMBER
# ca216/myshell

# myshell: myshell.c utility.c myshell.h
#     gcc -Wall myshell.c utility.c -o myshell

myshell: myshell.c utility.c mycommands.c myshell.h
	gcc -Wall myshell.c utility.c mycommands.c -o ../bin/myshell