# Duarte Martinho - 20410974
# ca216/myshell
# I acknowledge DCU's Academic Integrity Policy

myshell: myshell.c utility.c mycommands.c myshell.h
	gcc -Wall myshell.c utility.c mycommands.c -o ../bin/myshell